module.exports = [
  { id: "V001", name: "OKUNY INNOCENT", email: "okunyinnocent6@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V002", name: "APIO RACHEAL", email: "apiorachel22@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V003", name: "BIRUNGI ROBINAH", email: "robinahbirungi2002@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V004", name: "OWINY JEREMIAH", email: "owinyjeremiah2911@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V005", name: "ABER JACOB", email: "aberjacob732@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V006", name: "AWIR ISAAC", email: "isaacawio52@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V007", name: "OLYEMO JOSEPHAT", email: "josephatlyema@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V008", name: "ADIO FELIX", email: "odiofelix45@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V009", name: "AKELLO MERCY", email: "akellomercy042@gmail.com", pin: "1242", voted: false, role: "voter" },
  { id: "V010", name: "OLAA NAUME", email: "ellanaume176@gmail.com", pin: "1243", voted: false, role: "voter" },
  { id: "V011", name: "ACHOLA VIVIAN", email: "vilmaachola@gmail.com", pin: "1244", voted: false, role: "voter" },
  { id: "V012", name: "ACENG DELIGHT RUTH", email: "acengdelightruth@gmail.com", pin: "1245", voted: false, role: "voter" },
  { id: "V013", name: "ARAC BENEDICT", email: "benedictarachmedical@gmail.com", pin: "1246", voted: false, role: "voter" },
  { id: "V014", name: "EJANG MONICA", email: "ejangmonica51@gmail.com", pin: "1247", voted: false, role: "voter" },
  { id: "V015", name: "OTIM JACOB", email: "otimjacob05@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V016", name: "ONYONG SAMSON", email: "onyongsamson24@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V017", name: "OGWENG VINCENT", email: "ogwengvincent88@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V018", name: "ODONGO SOLOMON", email: "odongosolomon1234@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V019", name: "ACHUMA MARK", email: "karm.qs@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V020", name: "ACAR SILAS RONNIE", email: "kingniesil@gmail.com", pin: "1242", voted: false, role: "voter" },
  { id: "V021", name: "AWOR ESTELLA", email: "aworestella@gamil.com", pin: "1243", voted: false, role: "voter" },
  { id: "V022", name: "RABECCA LOYCE", email: "rabeccaloyceapio@gmail.com", pin: "1244", voted: false, role: "voter" },
  { id: "V023", name: "OBUA JANAN", email: "JananJandybestheart@gmail.com", pin: "1245", voted: false, role: "voter" },
  { id: "V024", name: "AMONGI DANIELA DOLLY", email: "amonydiana288@gmail.com", pin: "1246", voted: false, role: "voter" },
  { id: "V025", name: "OBONGI DANIEL", email: "obongdaniel499@gmail.com", pin: "1247", voted: false, role: "voter" },
  { id: "V026", name: "OKWIR DICKENS", email: "dickensokwir180@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V027", name: "STEPHEN BONGONYINGE", email: "stpnchosen@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V028", name: "OCEN EMMANUEL", email: "emmaarege5@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V029", name: "OPILA EDWIN", email: "edwinopila@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V030", name: "ATOKE SARAH", email: "sarahatoke2021@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V031", name: "ONGEL TONNY", email: "tonnyongel20@gmail.com", pin: "1242", voted: false, role: "voter" },
  { id: "V032", name: "WONTWONI JIMMY", email: "wontwonij@gmail.com", pin: "1243", voted: false, role: "voter" },
  { id: "V033", name: "AGWENG LILLIAN", email: "Lillianagweng2002@gmail.com", pin: "1244", voted: false, role: "voter" },
  { id: "V034", name: "OKELLO WALTER", email: "okotwaltersh889@gmail.com", pin: "1245", voted: false, role: "voter" },
  { id: "V035", name: "OKULLO AMOS", email: "okulloamos21@gmail.com", pin: "1246", voted: false, role: "voter" },
  { id: "V036", name: "AKULLO WINNIE", email: "winnyakullo2002@gmail.com", pin: "1247", voted: false, role: "voter" },
  { id: "V037", name: "AUMA IRENE", email: "auma25308@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V038", name: "AJIWA RONALD", email: "ajiwaronald2@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V039", name: "AKELLO WINNIE", email: "akellow514@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V040", name: "SABITI DEOGRACIOUS", email: "deogracioussabiti@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V041", name: "ONGENG JACKSON", email: "ongengjackson2001@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V042", name: "OGWAL STEPHEN", email: "ogwal7056@gmail.com", pin: "1242", voted: false, role: "voter" },
  { id: "V043", name: "OGWAL GERALD", email: "ogwalgeraldokello17@gmail.com", pin: "1243", voted: false, role: "voter" },
  { id: "V044", name: "AKELLO WINNIE", email: "akello.winnie@stud.umu.ac.ug", pin: "1244", voted: false, role: "voter" },
  { id: "V045", name: "AYO ALBRIGHT", email: "albrightayo@gmail.com", pin: "1245", voted: false, role: "voter" },
  { id: "V046", name: "APIO COURAGE", email: "apiocourage40@gmail.com", pin: "1246", voted: false, role: "voter" },
  { id: "V047", name: "OGWAL JANAN", email: "jananogwal70@gmail.com", pin: "1247", voted: false, role: "voter" },
  { id: "V048", name: "OGWAL MUSA", email: "ogwalmusa8@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V049", name: "CONNIE SHARP", email: "conniesharpsky@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V050", name: "OGWANG ROBINSON", email: "robinsonogwang256@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V051", name: "EGWANG HARON", email: "egwangharon@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V052", name: "ALOBO FEDRICK", email: "alobofredrick@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V053", name: "OPIO LAZARUS", email: "opiolazarus256@gmail.com", pin: "1242", voted: false, role: "voter" },
  { id: "V054", name: "AKULLU SARAH LORNA", email: "akullosarahlorna@gmail.com", pin: "1243", voted: false, role: "voter" },
  { id: "V055", name: "AGWENG LILLIAN", email: "agweng.lillian@lasa.org", pin: "1244", voted: false, role: "voter" },
  { id: "V056", name: "OKUNY INNOCENT", email: "okuny.innocent@lasa.org", pin: "1245", voted: false, role: "voter" },
  { id: "V057", name: "EKUU AARON", email: "ekuu.aaron@lasa.org", pin: "1246", voted: false, role: "voter" },
  { id: "V058", name: "OLYEMA JOSEPHAT", email: "olyema.josephat@lasa.org", pin: "1247", voted: false, role: "voter" },
  { id: "V059", name: "ABER JACOB", email: "aber.jacob@lasa.org", pin: "1234", voted: false, role: "voter" },
  { id: "V060", name: "ODONGO SOLOMON", email: "odongo.solomon@lasa.org", pin: "1234", voted: false, role: "voter" },
  { id: "V061", name: "ONYONG SAMSON", email: "onyong.samson@lasa.org", pin: "1234", voted: false, role: "voter" },
  { id: "V062", name: "OWINY JEREMIAH", email: "owiny.jeremiah@lasa.org", pin: "1234", voted: false, role: "voter" },
  { id: "V063", name: "OTIM JACOB", email: "otim.jacob@lasa.org", pin: "1234", voted: false, role: "voter" },
  { id: "V064", name: "APIO RACHEAL", email: "apio.racheal@lasa.org", pin: "1242", voted: false, role: "voter" },
  { id: "V065", name: "AWOR ESTELLA", email: "awor.estella@lasa.org", pin: "1243", voted: false, role: "voter" },

  { id: "V066", name: "ABER JACOB", email: "aber.jacob@lasa.org", pin: "1234", voted: false, role: "voter" },
  { id: "V067", name: "AMONGI DOLLY DIANA", email: "amongidolly@gmail.com", pin: "1234", voted: false, role: "voter" },
  { id: "V068", name: "ARAC BENEDICT", email: "arac.benedict@lasa.org", pin: "1234", voted: false, role: "voter" },
  { id: "V069", name: "ACENG DELIGHT RUTH", email: "aceng.delight@lasa.org", pin: "1234", voted: false, role: "voter" },

  { id: "A001", name: "Admin", email: "agashaalex@gmail.com", pin: "0000", voted: false, role: "admin" }
];